version: '3'
services:
  db:
    image: postgres:14.2-alpine
    container_name: postgres14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: "postgres -c 'max_connections=500'"
    environment:
      POSTGRES_DB: db_webapp
      POSTGRES_USER: usr_webapp
      POSTGRES_PASSWORD: secret!
    ports:
      - "5432:5432"
  webapp:
    container_name: webapp
    build: .
    command: "bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      DB_HOST: db
      DB_NAME: db_webapp
      DB_USERNAME: usr_webapp
      DB_PASSWORD: secret!
    volumes:
      - .:/app:cached
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  postgres_data: {}
networks:
  default:
    name: webapp_default